# Generated by Django 6.0.4 on 2026-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.AddField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(to='hub.branch'),
        ),
    ]
