# Generated by Django 6.0.4 on 2026-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_remove_subject_branch_subject_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(blank=True, to='hub.branch'),
        ),
    ]
