# Generated by Django 6.0.4 on 2026-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_filecategory_remove_file_pdf_remove_file_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
