# Generated by Django 6.0.4 on 2026-05-09 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_file_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_common',
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hub.filecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='Untitled PDF', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(to='hub.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
