# Generated by Django 6.0.4 on 2026-05-09 17:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_remove_subject_is_common_alter_file_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
